### ISSUE TITLE
Support for non-system Python interpreter?

### ISSUE THREAD

**Issue by j0hnm4r5** [chaosct/ofxPython#2]
This is probably related to issue #1. For OSX, are user-installed Python interpreters or even virtualenvs possible?

**Comment by chaosct** [comment]
Ok, this has two different parts:

#### Alternative Python interpreters

That can be achieved simply by changing the include/linking paths so that they point to the desired Python. Maybe a section in the README explaining that could be useful...

#### Virtualenvs

This is a matter of library paths. If you add the path to your env site-packages it should work, I think... An example demonstrating this would be great.

I leave this issue open until those aspects are documented

**Comment by chaosct** [comment]
I've found the explaination for the virtualenv case: [Getting an embedded Python runtime to use the current active virtualenv](http://stackoverflow.com/a/9071047/230866)

**Comment by stuaxo** [comment]
Hi,
   You can check the VIRTUAL_ENV environment variable to get a path to the current env.

Cheers
S

**Comment by chaosct** [comment]
Activating a virtualenv is now supported with `void ofxPython::setVirtualEnv(const string & path)`, where `path` is the virtualenv _folder_ ( without the `bin/activate_this.py` part).

@stuaxo I think I'd prefer not having this done automatically. It is always possible to check the env variable in OF and use the `setVirtualEnv` method.
